@port = {{$dotenv PORT}}
@URL = http://localhost:{{port}}/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5NWY4MGM1LTJmMzktNGYxNS04ZjU0LWViYzA0OTdjMDkwZiIsImlhdCI6MTY3ODc2MzA3NCwiZXhwIjoxNjc4NzY2Njc0fQ.RUJFZB0xE-aWKN99jS2a9_g5CXUaUxGcZkk1zLukcFo

###
POST {{URL}}/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Aa1#User"
}
###
POST {{URL}}/auth/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Aa1#User",
  "name": "User Test"
}
###
POST {{URL}}/auth/refresh
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}
###
POST {{URL}}/auth/logout
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}
###
POST {{URL}}/auth/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

user@test.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Aa1#User
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

User Test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="example.jpg"
Content-Type: image/jpg

< ./example.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--