
@port = {{$dotenv PORT}}
@URL = http://localhost:{{port}}/api

### Sing In
POST {{URL}}/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Aa1#User"
}

### Sing Up
POST {{URL}}/auth/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Aa1#User",
  "name": "User Test"
}


### refresh token
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkZWE2MGNiLTc2NzYtNDAzYS05MDE1LTIyNjY0ODgxYjg1YSIsImlhdCI6MTY3ODAwMDMzNSwiZXhwIjoxNjc4MDAzOTM1fQ.hcym5t1KOKAxxXKbKRnphqY4UBDs1ucvzC3t9CP6FD4

POST {{URL}}/auth/refresh
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}

###
POST {{URL}}/auth/logout
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}

###
POST {{URL}}/auth/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

user@test.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Aa1#User
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

User Test
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="example.png"
Content-Type: image/png

< ./example.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--