@port = {{$dotenv PORT}}
@URL = http://localhost:{{port}}/api
@userId = 495f80c5-2f39-4f15-8f54-ebc0497c090f
@userCookie = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5NWY4MGM1LTJmMzktNGYxNS04ZjU0LWViYzA0OTdjMDkwZiIsImlhdCI6MTY3ODc2NDMzNSwiZXhwIjoxNjc4NzY3OTM1fQ.6vF4fNPAOZiZIuQWwLb-pvmRxQuz4kb2X9lxGOF3X0k; Max-Age=60; Path=/; Expires=Mon, 13 Mar 2023 23:13:33 GMT; HttpOnly; Secure; SameSite=Strict
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5NWY4MGM1LTJmMzktNGYxNS04ZjU0LWViYzA0OTdjMDkwZiIsImlhdCI6MTY3ODc2NDMzNSwiZXhwIjoxNjc4NzY3OTM1fQ.6vF4fNPAOZiZIuQWwLb-pvmRxQuz4kb2X9lxGOF3X0k

###
GET {{URL}}/user

###
GET {{URL}}/user/{{userId}}

###
DELETE {{URL}}/user
Cookie: {{userCookie}}
# Authorization: Bearer {{TOKEN}}

###
PUT {{URL}}/user
Authorization: Bearer {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

update name User
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Aa2#User
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="example.jpg"
Content-Type: image/jpg

< ./example.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--